unstable_features = true
edition = "2021"


max_width = 120
chain_width = 60
blank_lines_upper_bound = 2


use_field_init_shorthand = true
enum_discrim_align_threshold = 20
struct_field_align_threshold = 20


imports_layout = "HorizontalVertical"
imports_granularity = "Module"
group_imports = "StdExternalCrate"


force_multiline_blocks = false
match_block_trailing_comma = true


reorder_impl_items = true


format_macro_matchers = true
format_macro_bodies = true

format_code_in_doc_comments = true
normalize_comments = true
normalize_doc_attributes = true


use_try_shorthand = true
condense_wildcard_suffixes = true
